import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    absolute: "",
    default: "NextJS 14 Practice",
    template: "%s | NextJS template",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  hash,
}: Readonly<{
  children: React.ReactNode;
  hash: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className="w-100 pr-5 pl-5 bg-gray-400">header</h1>
        {hash}
        {children}
        <h1 className="w-100 pr-5 pl-5 bg-gray-400">footer</h1>
      </body>
    </html>
  );
}
